---
name: ElixirFM
version: 1.1
author:
  - 'Otakar Smrz <otakar smrz mff cuni cz>'
abstract: The great new ElixirFM!
license: gpl
resources:
  license: http://www.opensource.org/licenses/gpl-license.php
build_requires:
  Test::More: 0
provides:
  ElixirFM:
    file: lib/ElixirFM.pm
    version: 1.1
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
