---
name: ElixirFM
version: 1.1
author:
  - 'Otakar Smrz <otakar smrz mff cuni cz>'
abstract: Interfaces to the ElixirFM system implementing Functional Arabic Morphology
license: gpl
resources:
  license: ~
requires:
  Encode::Arabic: 0
  perl: 5.008
build_requires:
  Encode::Arabic: 0
  Test::More: 0
provides:
  ElixirFM:
    file: lib/ElixirFM.pm
    version: 1.1
  ElixirFM::CGI:
    file: lib/ElixirFM/CGI.pm
    version: 1.1.946
  ElixirFM::CGI::Derive:
    file: lib/ElixirFM/CGI/Derive.pm
    version: 1.1.946
  ElixirFM::CGI::Inflect:
    file: lib/ElixirFM/CGI/Inflect.pm
    version: 1.1.946
  ElixirFM::CGI::Lookup:
    file: lib/ElixirFM/CGI/Lookup.pm
    version: 1.1.946
  ElixirFM::CGI::Resolve:
    file: lib/ElixirFM/CGI/Resolve.pm
    version: 1.1.964
  ElixirFM::Exec:
    file: lib/ElixirFM/Exec.pm
    version: 1.1.946
  ElixirFM::Resolve:
    file: lib/ElixirFM/Resolve.pm
    version: 1.1
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
