---
abstract: 'Interfaces to the ElixirFM system implementing Functional Arabic Morphology'
author:
  - 'Otakar Smrz <otakar smrz mff cuni cz>'
build_requires:
  Encode::Arabic: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ElixirFM
provides:
  ElixirFM:
    file: lib/ElixirFM.pm
    version: 1.2
  ElixirFM::CGI:
    file: lib/ElixirFM/CGI.pm
    version: v1.2.1022
  ElixirFM::CGI::Derive:
    file: lib/ElixirFM/CGI/Derive.pm
    version: v1.1.1031
  ElixirFM::CGI::Inflect:
    file: lib/ElixirFM/CGI/Inflect.pm
    version: v1.1.1031
  ElixirFM::CGI::Lookup:
    file: lib/ElixirFM/CGI/Lookup.pm
    version: v1.1.1031
  ElixirFM::CGI::Resolve:
    file: lib/ElixirFM/CGI/Resolve.pm
    version: v1.1.984
  ElixirFM::Exec:
    file: lib/ElixirFM/Exec.pm
    version: v1.1.987
  ElixirFM::Resolve:
    file: lib/ElixirFM/Resolve.pm
    version: 1.1
requires:
  Encode::Arabic: 0
  perl: 5.008
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 1.2
